version: '3'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: badger_db
      MONGO_INITDB_ROOT_USERNAME: hidayatullahagung
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - 27020:27017
    volumes:
      - mongodb_data_container:/data/db
  calypso:
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/calypso
        port: 3001
    environment:
      - APP_NAME=calypso
    ports:
      - 8001:3000
    restart: on-failure
    volumes:
      - ./golang:/usr/src/app
    networks:
      - monorepo_net
  echo:
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/echo
        port: 3001
    environment:
      - APP_NAME=echo
    ports:
      - 8002:3000
    restart: on-failure
    volumes:
      - ./golang:/usr/src/app
    networks:
      - monorepo_net
networks:
  monorepo_net:
    driver: bridge
volumes:
  mongodb_data_container:
