version: '3'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: badger_db
      MONGO_INITDB_ROOT_USERNAME: hidayatullahagung
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - 27020:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - monorepo_net
  user_service:
    depends_on:
      - mongodb_container
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/user_service
    environment:
      - APP_ENV=dev
      - DB_HOST=mongodb_container
      - DB_PORT=27017
      - DB_NAME=badger_db
      - DB_AUTH=
      - DB_USERNAME=hidayatullahagung
      - DB_PASSWORD=12345678
      - DB_POOL=100
      - GRPC_PORT=9000
    ports:
      - 9091:9000
    restart: on-failure
    volumes:
      - ./golang:/usr/src/app
    networks:
      - monorepo_net
  auth_service:
    depends_on:
      - mongodb_container
      - user_service
    build:
      context: ./golang
      dockerfile: ./Dockerfile
      args:
        project: ./cmd/auth_service
    environment:
      - APP_ENV=dev
      - DB_HOST=mongodb_container
      - DB_PORT=27017
      - DB_NAME=badger_db
      - DB_AUTH=
      - DB_USERNAME=hidayatullahagung
      - DB_PASSWORD=12345678
      - DB_POOL=100
      - GRPC_PORT=9000
      - HOST_GRPC_USER_SERVICE=user_service:9000
    ports:
      - 9092:9090
    restart: on-failure
    volumes:
      - ./golang:/usr/src/app
    networks:
      - monorepo_net
networks:
  monorepo_net:
    driver: bridge
volumes:
  mongodb_data_container:
